parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    env(DATABASE_BIS_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                url: '%env(resolve:DATABASE_URL)%'
            bis:
                driver: 'pdo_mysql'
                server_version: '5.5'
                charset: utf8mb4
                url: '%env(resolve:DATABASE_BIS_URL)%'
                schema_filter: ~^(?!view_)~
                mapping_types:
                     enum: string
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    datetime_functions:
                        year: DoctrineExtensions\Query\Mysql\Year
                        week: DoctrineExtensions\Query\Mysql\Week
                        quarter: DoctrineExtensions\Query\Mysql\Quarter
                        month: DoctrineExtensions\Query\Mysql\Month
                        day: DoctrineExtensions\Query\Mysql\Day
                        hour: DoctrineExtensions\Query\Mysql\Hour
                        minute: DoctrineExtensions\Query\Mysql\Minute
                        now: DoctrineExtensions\Query\Mysql\Now
                        dateadd: DoctrineExtensions\Query\Mysql\DateAdd
                        datesub: DoctrineExtensions\Query\Mysql\DateSub
                        datediff: DoctrineExtensions\Query\Mysql\DateDiff
                    string_functions:
                        concat_ws: DoctrineExtensions\Query\Mysql\ConcatWs
                        regexp: DoctrineExtensions\Query\Mysql\Regexp
            bis:
                connection: bis
                mappings:
                    BisBundle:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/BisBundle/Entity'
                        prefix: 'BisBundle\Entity'
                        alias: BisBundle
                dql:
                    datetime_functions:
                        year: DoctrineExtensions\Query\Mysql\Year
                        week: DoctrineExtensions\Query\Mysql\Week
                        quarter: DoctrineExtensions\Query\Mysql\Quarter
                        month: DoctrineExtensions\Query\Mysql\Month
                        day: DoctrineExtensions\Query\Mysql\Day
                        hour: DoctrineExtensions\Query\Mysql\Hour
                        minute: DoctrineExtensions\Query\Mysql\Minute
                        now: DoctrineExtensions\Query\Mysql\Now
                        dateadd: DoctrineExtensions\Query\Mysql\DateAdd
                        datesub: DoctrineExtensions\Query\Mysql\DateSub
                        datediff: DoctrineExtensions\Query\Mysql\DateDiff
                    string_functions:
                        concat_ws: DoctrineExtensions\Query\Mysql\ConcatWs
                        regexp: DoctrineExtensions\Query\Mysql\Regexp
        auto_generate_proxy_classes: "%kernel.debug%"
