parameters:
    locales: ['en','fr','nl']
    default_locale: 'en'
framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%default_locale%'
    csrf_protection: ~
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: snc_redis.session.handler
        cookie_secure: auto
        cookie_samesite: lax

    #esi: ~
    fragments: ~
    php_errors:
        log: true
