httplug:
    plugins:
        logger: ~
    clients:
        app:
            factory: 'httplug.factory.guzzle6'
            plugins: ['httplug.plugin.logger']
            config:
                timeout: 2
