parameters:
    env(LOCO_API_KEY): ''

translation:
    locales: '%app.locales%'
    http_client: 'httplug.client.app'
    edit_in_place:
        enabled: false
        config_name: app
    configs:
        app:
            dirs: ["%kernel.project_dir%/templates", "%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            remote_storage: ["php_translation.adapter.loco"]

translation_adapter_loco:
    projects:
        messages:
            api_key: '%env(resolve:LOCO_API_KEY)%'

jms_i18n_routing:
    default_locale: '%locale%'
    locales: '%app.locales%'
    strategy: prefix_except_default