security:
    encoders:
        App\Entity\User:
            id: AuthBundle\Security\SHA1PasswordEncoder

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_MANAGE_USER, ROLE_SMS_ADMIN]
        ROLE_SMS_ADMIN: [ROLE_SMS]
        ROLE_SMS: [ROLE_USER]
        ROLE_USER: [IS_AUTHENTICATED]

    always_authenticate_before_granting: true

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        adlap:
            entity: { class: App\Entity\User, property: email }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - AuthBundle\Security\AdldapAuthenticator
            provider: adlap
            stateless: true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 86400     # 1 day
                path: /
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                always_remember_me: true
            logout:
                path: security_logout
                target: security_login

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/translation/, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
