framework:
    default_locale: '%default_locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        enabled_locales: [ 'en', 'fr', 'nl' ]
        fallbacks:
            - en
        providers:
            loco:
                dsn: '%env(LOCO_DSN)%'
                domains: [ 'messages' ]
                locales: [ 'en', 'fr', 'nl' ]
