build:
    environment:
        mysql: 5.7
        php:
            version: 7.2
            ini:
                'date.timezone': 'Europe/Brussels'
    tests:
        override:
            -
                command: 'bin/phpunit'
                coverage:
                    file: './var/coverage.xml'
                    format: 'clover'
            -
                command: phpcs-run --standard=checkstyle.xml
                use_website_config: false

filter:
    paths:
        - 'src/*'

before_commands:
    - 'composer install --no-interaction --no-scripts'
    - 'php bin/console doctrine:database:create --env=test'
    - 'php bin/console doctrine:schema:create --env=test'
    - 'php bin/console doctrine:fixtures:load -n --env=test'

tools:
    sensiolabs_security_checker: true
    php_loc: true
    php_pdepend: true
    php_sim: true
    php_changetracking: true
    php_mess_detector:
        config:
            ruleset: ./codesize.xml
