language: php
services:
  - mysql
cache:
  directories:
    - $HOME/.composer/cache/files
matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
env:
  - APP_ENV=test SYMFONY_VERSION="4.0.*" DB=mysql
before_install:
  - echo "extension=ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test
script:
  - ./bin/phpunit
notifications:
  email: damien.lagae@enabel.be
