language: php
matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
env:
  - APP_ENV=test
before_install:
  - composer self-update
install:
  - cp .env.travis .env
  - composer install
script:
  - phpunit
notifications:
  email: damien.lagae@enabel.be
