version: '3'
services:
  mariadb:
    image: mariadb
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: admanager
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - 3306:3306
    labels:
      com.symfony.server.service-prefix: 'DATABASE'

  bis:
    image: mariadb
    volumes:
      - ~/Projects/BIS/.db/data:/var/lib/mysql/
      - ~/Projects/BIS/.db/log:/var/log/mysql/
      - ~/Projects/BIS/.db/conf:/etc/mysql/conf.d/
    environment:
      MYSQL_DATABASE: bis
      MYSQL_USER: bisreader
      MYSQL_PASSWORD: 'elephpant401'
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: bis,mariadb
      PMA_USER: root
      PMA_PASSWORD: toor
    ports:
      - 8080:80
    links:
      - mariadb
      - bis

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
    labels:
      com.symfony.server.service-prefix: 'MAILER'
