db:
  image: mariadb
  volumes:
    - ./.db/data:/var/lib/mysql/
    - ./.db/log:/var/log/mysql/
    - ./.db/conf:/etc/mysql/conf.d/
  environment:
    MYSQL_DATABASE: admanager
    MYSQL_USER: admanager
    MYSQL_PASSWORD: admanager
    MYSQL_ROOT_PASSWORD: toor
  ports:
    - 3306:3306

bis:
  image: mariadb
  volumes:
    - ~/Projects/BIS/.db/data:/var/lib/mysql/
    - ~/Projects/BIS/.db/log:/var/log/mysql/
    - ~/Projects/BIS/.db/conf:/etc/mysql/conf.d/
  environment:
    MYSQL_DATABASE: bis
    MYSQL_USER: bisreader
    MYSQL_PASSWORD: 'elephpant401'
    MYSQL_ROOT_PASSWORD: toor
  ports:
    - 3307:3306

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links: 
    - db
    - bis
  environment:
    PMA_HOSTS: db,bis
    PMA_USER: root
    PMA_PASSWORD: toor
  restart: always
  ports:
    - 8080:80
