version: '3'
services:
  mariadb:
    image: mariadb:10.1
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: admanager
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - 3306:3306
    labels:
      com.symfony.server.service-prefix: 'DATABASE'

  bis:
    image: mysql:5.5
    volumes:
      - ~/Projects/BIS/.db/data:/var/lib/mysql/
      - ~/Projects/BIS/.db/log:/var/log/mysql/
      - ~/Projects/BIS/.db/conf:/etc/mysql/conf.d/
    environment:
      MYSQL_DATABASE: bis
      MYSQL_USER: bisreader
      MYSQL_PASSWORD: 'elephpant401'
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: bis,mariadb
      PMA_USER: root
      PMA_PASSWORD: toor
    ports:
      - 8080:80
    depends_on:
      - mariadb
      - bis

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
    labels:
      com.symfony.server.service-prefix: 'MAILER'

  redis:
    image: redis
    volumes:
      - .docker/data/redis:/data
    ports:
      - 6379:6379
    labels:
      com.symfony.server.service-prefix: 'REDIS'

  ## PHP Part
  ## TODO: Add php ext (ldap, curl, json, intl, mysql, xml)
  ## TODO2: Create a install/entrypoint script
  php72:
    image: php:7.2-fpm
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 72:8000
    entrypoint: /app/symfony serve

  php74:
    image: php:7.4-fpm
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 74:8000
    entrypoint: /app/symfony serve

  php80:
    image: php:8.0-fpm
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 80:8000
    entrypoint: /app/symfony serve