<?php

namespace BisBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BisPersonSfRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BisPersonSfRepository extends EntityRepository
{
}
