imports:
    - { resource: parameters.yml }

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool:
        type: memory
        path: '%kernel.project_dir%/var/spool'

#doctrine_migrations:
#    dir_name: "%kernel.root_dir%/DoctrineMigrations"
#    namespace: Application\Migrations
#    table_name: migration_versions
#    name: Application Migrations
#    organize_migrations: false

#
#jms_di_extra:
#    automatic_controller_injections:
#        properties:
#            request: "@request"
#            router: "@router"
#
#        method_calls:
#            setRouter: ["@router"]
#    disable_grep: true
#
#jms_translation:
#    configs:
#        app:
#          dirs: ['%kernel.root_dir%', '%kernel.root_dir%/../src/AppBundle']
#          output_dir: '%kernel.root_dir%/../src/AppBundle/Resources/translations'
#          ignored_domains: [routes]
#          excluded_names: ["*TestCase.php", "*Test.php"]
#          excluded_dirs: [cache, data, logs]
#        auth:
#            dirs: ['%kernel.root_dir%', '%kernel.root_dir%/../src/AuthBundle']
#            output_dir: '%kernel.root_dir%/../src/AuthBundle/Resources/translations'
#            ignored_domains: [routes]
#            excluded_names: ["*TestCase.php", "*Test.php"]
#            excluded_dirs: [cache, data, logs]
#        bis:
#            dirs: ['%kernel.root_dir%', '%kernel.root_dir%/../src/BisBundle']
#            output_dir: '%kernel.root_dir%/../src/BisBundle/Resources/translations'
#            ignored_domains: [routes]
#            excluded_names: ["*TestCase.php", "*Test.php"]
#            excluded_dirs: [cache, data, logs]
#
#jms_i18n_routing:
#    default_locale: en
#    locales: '%app.locales%'
#    strategy: prefix_except_default

translation:

    symfony_profiler: # must be placed in config_dev.yml
        enabled: true
    webui:
        enabled: true
    edit_in_place:
        activator: php_translation.edit_in_place.activator
    configs:
        app:
            dirs: ['%kernel.root_dir%', '%kernel.root_dir%/Resources/views', '%kernel.root_dir%/../src']
            output_dir: '%kernel.root_dir%/Resources/translations'
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            remote_storage: ["php_translation.adapter.loco"]

translation_adapter_loco:
  projects:
    messages:
      api_key: 'BQtDiLdqFbhpKQ_DvIUV9tYMDKK481J0F'

