<?php

namespace App\Repository;

use App\Entity\Application;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Application::class);
    }

    /**
     * @return Application[]
     *
     * @throws \Doctrine\ORM\Query\QueryException
     */
    public function findAllApplications()
    {
        return $this->createQueryBuilder('application')
            ->addCriteria(self::createActiveCriteria())
            ->getQuery()
            ->execute();
    }

    public static function createActiveCriteria()
    {
        return Criteria::create()
            ->andWhere(Criteria::expr()->eq('enable', 1));
    }
}
