---
- name: CRONTAB | AD Sync noon [1 pm]
  cron:
    name: Synchronize person between GO4HR and ActiveDirectory (1pm)
    minute: "0"
    hour: "13"
    state: present
    user: root
    job: "{{ release_console_path }} ad:crontask:synchronize --env={{ application_env }} > {{ release_logs_path }}/ad_sync_noon.log"
  when: application_env == 'prod'

- name: CRONTAB | AD Sync morning [1 am]
  cron:
    name: Synchronize person between GO4HR and ActiveDirectory (1am)
    minute: "0"
    hour: "1"
    state: present
    user: root
    job: "{{ release_console_path }} ad:crontask:synchronize --env={{ application_env }} > {{ release_logs_path }}/ad_sync_morning.log"
  when: application_env == 'prod'

- name: CRONTAB | AD Sync morning [7 am]
  cron:
    name: Synchronize person between GO4HR and ActiveDirectory (7am)
    minute: "0"
    hour: "7"
    state: present
    user: root
    job: "{{ release_console_path }} ad:crontask:synchronize --env={{ application_env }} > {{ release_logs_path }}/ad_sync_morning.log"
  when: application_env == 'prod'