---
- name: Send notification message via Slack all options
  slack:
    token: "{{ slack_token }}"
    domain: "{{ slack_domain }}"
    msg: 'Server: {{ ansible_hostname }} | Get translation from localize.biz [Loco]'
    username: "{{ slack_headline }}"
    icon_url: "{{ slack_icon_url }}"
    channel: "{{ slack_channel }}"
    parse: 'none'
  delegate_to: localhost

- name: Sync translation with localize.biz [loco]
  command: '{{ release_console_path }} translation:download'

- name: Send notification message via Slack all options
  slack:
    token: "{{ slack_token }}"
    domain: "{{ slack_domain }}"
    msg: 'Server: {{ ansible_hostname}} | Clear cache'
    username: "{{ slack_headline }}"
    icon_url: "{{ slack_icon_url }}"
    channel: "{{ slack_channel }}"
    parse: 'none'
  delegate_to: localhost

- name: Clear the cache
  command: '{{ release_console_path }} cache:clear'

- name: Add write permissions
  file:
    state: directory
    path: "{{ release_var_path }}"
    owner: "apache"
    group: "apache"
    recurse: yes
    mode: "u=rxw,g=rxw,o=rw"

- name: Send notification message via Slack all options
  slack:
    token: "{{ slack_token }}"
    domain: "{{ slack_domain }}"
    msg: 'Server: {{ ansible_hostname }} | Install cron task :timer_clock:'
    username: "{{ slack_headline }}"
    icon_url: "{{ slack_icon_url }}"
    channel: "{{ slack_channel }}"
    parse: 'none'
  delegate_to: localhost

- name: CRONTAB | AD Sync noon [1 pm]
  cron:
    name: Synchronize person between GO4HR and ActiveDirectory (1pm)
    minute: "0"
    hour: "13"
    weekday: "1-5"
    state: present
    user: root
    job: "{{ release_console_path }} ad:crontask:synchronize --env={{ application_env }} > {{ release_logs_path }}/ad_sync_noon.log"
  when: application_env == 'prod'

- name: CRONTAB | AD Sync morning [1 am]
  cron:
    name: Synchronize person between GO4HR and ActiveDirectory (1am)
    minute: "0"
    hour: "1"
    weekday: "1-5"
    state: present
    user: root
    job: "{{ release_console_path }} ad:crontask:synchronize --env={{ application_env }} > {{ release_logs_path }}/ad_sync_morning.log"
  when: application_env == 'prod'

- name: CRONTAB | AD Sync morning [7 am]
  cron:
    name: Synchronize person between GO4HR and ActiveDirectory (7am)
    minute: "0"
    hour: "7"
    weekday: "1-5"
    state: present
    user: root
    job: "{{ release_console_path }} ad:crontask:synchronize --env={{ application_env }} > {{ release_logs_path }}/ad_sync_morning.log"
  when: application_env == 'prod'


- name: CRONTAB | LDAP cleanup [2 am]
  cron:
    name: Cleanup entry/person who are no longer in GO4HR (2am)
    minute: "0"
    hour: "2"
    weekday: "1-5"
    state: absent
    user: root
    job: "{{ release_console_path }} ad:crontask:ldap --env={{ application_env }} > {{ release_logs_path }}/ad_sync_morning.log"
  when: application_env == 'prod'

- name: Send notification message via Slack all options
  slack:
    token: "{{ slack_token }}"
    domain: "{{ slack_domain }}"
    msg: 'Server: {{ ansible_hostname }} | Deployed ! :trophy:'
    username: "{{ slack_headline }}"
    icon_url: "{{ slack_icon_url }}"
    channel: "{{ slack_channel }}"
    parse: 'none'
  delegate_to: localhost