---
# Database vars
database_host: '{{ vault_database_host }}'
database_user: '{{ vault_database_user }}'
database_password: '{{ vault_database_password }}'
database_name: 'password'

# BIS vars
bis_database: 'bis'
bis_user: '{{ vault_bis_user }}'
bis_password: '{{ vault_bis_password }}'

# AD vars
ad_base_dn: 'dc=ad4dev,dc=local'
ad_user: '{{ vault_ad_user }}'
ad_password: '{{ vault_ad_password }}'
ad_account_suffix: 'ad4dev.local'
ad_mail_domain: 'enabel.be'
ad_home_drive: 'U:'
ad_home_base_directory: '\\\\ad4dev.local\\dfs1\\homes$\\'

# AD Notification vars
ad_notification_from: 'noreply@enabel.be'
ad_notification_to: 'ersin.yuksel@enabel.be,francoise.simkens@enabel.be,damien.lagae@enabel.be'

# GIT vars
deploy_key_public: '{{ vault_deploy_key_public }}'
deploy_key_private: '{{ vault_deploy_key_private }}'
github_oauth_token: '{{ vault_github_oauth_token }}'

# Slack vars
slack_token: "{{ vault_slack_token }}"
slack_domain: "{{ vault_slack_domain }}"
slack_headline: "Ansistrano"
slack_icon_url: "https://cdn4.iconfinder.com/data/icons/boy-hair-and-face/100/face6-512.png"
slack_channel: "#dev"

# Loco vars
loco_api_key: "{{ vault_loco_api_key }}"

# SuccessFactor vars
sf_api_url: 'https://api012.successfactors.eu/odata/v2/'
sf_api_token: '{{ vault_sf_api_token }}'
sf_api_secret: '{{ vault_sf_api_secret }}'

# SmsGateway.me vars
sms_gateway_me_api_token: "{{ vault_sms_gateway_me_api_token }}"
sms_gateway_me_device_id: "{{ vault_sms_gateway_me_device_id }}"

# Api key for intranet iframe
intranet_api_key: "{{ vault_intranet_api_key }}"