app:
    resource: "../src/AppBundle/Controller/"
    type:     annotation
    prefix:   /

auth:
    resource: '../src/AuthBundle/Controller/'
    type:     annotation
    prefix:   /
    options: { i18n: false }

