auth:
    resource: '../src/AuthBundle/Controller/'
    type:     annotation
    prefix:   /
    options: { i18n: false }

api:
    resource: '../src/ApiBundle/Controller/'
    type:     annotation
    prefix:   /api
    options: { i18n: false }
