auth:
    resource: '../src/Auth/Controller/'
    type:     annotation
    prefix:   /
    options: { i18n: false }

api:
    resource: '../src/Api/Controller/'
    type:     annotation
    prefix:   /api
    options: { i18n: false }
